### ISSUE TITLE
[Suggestion] Contact on User Page

### ISSUE THREAD

**Issue by jgarlic69** [PawCorp/walltaker#12]
Currently there is the issue that if you want to leave a contact option to you have to take up space inside link's terms for that. My suggestion is that on each user's page there should be a space to provide means of contacting you be it Discord, Telegram or anything else.

**Comment by pupgray** [comment]
Hi! For the moment, I've added an open text field for user profile! You can list any contact details here!


<img width="844" alt="Capture d’écran, le 2022-03-12 à 19 07 10" src="https://user-images.githubusercontent.com/83324179/158039534-982e4a65-5947-433d-b899-50486d73e533.png">
