### ISSUE TITLE
[Suggestion] Add different titles for each page/view

### ISSUE THREAD

**Issue by NameNotFinal** [PawCorp/walltaker#13]
Currently it can get quite difficult to navigate, if you're like me and like to open new tabs constantly, since all the tabs are just titled "Walltaker". So I suggest that each view gets a different title, like for example if you're on a user page it says "{username} - Walltaker" or something to that effect. Would be extremely useful.

**Comment by pupgray** [comment]
Done! Just deployed this! Titles should now appear much more descriptive
<img width="210" alt="Capture d’écran, le 2022-03-12 à 15 22 24" src="https://user-images.githubusercontent.com/83324179/158033745-b6aba9a9-a9ea-4c54-8270-1ef03d61784e.png">

**Comment by NameNotFinal** [comment]
Thanks!
