### ISSUE TITLE
[Enhancement] Time since last change on Link-Page

### ISSUE THREAD

**Issue by Lycraon** [PawCorp/walltaker#15]
It would help to see when a wallpaper on a link was last changes, so i don't change one imidiately after someone else did.

**Comment by Pauly2000** [comment]
Another interessting feature would be to change the time the wallpaper stays on your screen(PC and Phone) before returning to default. (only makes sense when both last changed and wallpaper duration is on link site)

**Comment by pupgray** [comment]
Noted! It'd be quite easy to add a timestamp, so I'll add that today!

As for the other thing you mentioned with a minimum time, I think that's better handled at the client side IMO, open to debate on that. Would have to cache 2 copies of the link, one for the "current one" and another for "pending"

**Comment by pupgray** [comment]
![Capture d’écran, le 2022-04-03 à 21 11 11](https://user-images.githubusercontent.com/83324179/161458413-e8ac461b-f816-4a8a-b773-3ece52bbd2a6.png)

Added!

**Comment by pupgray** [comment]
Going to close this for now, we can circle back on the minimum time in clients in a Go Client ticket maybe?
