### ISSUE TITLE
[Bug] Loading (link).json causes Website to reanimate reacton to link even when nothing changed

### ISSUE THREAD

**Issue by Lycraon** [PawCorp/walltaker#16]
When i fetch the .json via JavaScript/NVMEscript the reaction that is shown under Link on Webpage is being reloaded.

Maybe im doing something wrong, but my requests should no be able to do that.

Possible fix:
only reload/reanimate when reaction or anything else(besides last_updated) changed

**Comment by Pauly2000** [comment]
Nevermind bug stoped showing maybe it was because of issue#17
