### ISSUE TITLE
[Enhancement?] Sort 'browse' list by time of last change.

### ISSUE THREAD

**Issue by Deanskond** [PawCorp/walltaker#20]
(Also show timestamp of last change there, like in issue 15)
That way so the ones recently changed would be on bottom, pushing ones which aren't the longest to top.

**Comment by Deanskond** [comment]
Well, I don't think it would be very wise to do it server side.

**Comment by pupgray** [comment]
The query isn't HORRIBLE, about ~300ms on average, which I'm OK with here. Going to monitor this for a bit, but the sorting is live!
