### ISSUE TITLE
[Custom Client] in Automate

### ISSUE THREAD

**Issue by Deanskond** [PawCorp/walltaker#21]
_Ok, this may not be the best place to write this, but discord doesn't want to allow me to create new account. As it's not exactly an issue, but that seemed the best way to message._

Since android client wasn't changing my wallpaper automatically on Android 8.0, (changing it only after I press "refresh")

 I decided to create my own simple one in Automate
 https://github.com/Deanskond/walltaker_automate
 
 It allows to select which screens should be affected (system wallpaper and/or lock screen), it may be easily duplicated to allow different ids for each.
 
 <details><summary>
 It introduces itself:</summary>
Request header
{ "User_Agent":"walltaker-android-automate/0.9"}</details>

**Comment by pupgray** [comment]
AWESOME, thanks so much for adding a user agent, I have a few more clients that I need to add status markers for. I'll add this one shortly!

Do you want this listed on the website and readme? Would love to add it! :)

**Comment by Deanskond** [comment]
Seeing it there would be very nice ;). Now I have much higher motivation to overcame limitations and problems I encountered in it.

**Comment by pupgray** [comment]
Added! Thanks so much! :) @Lycraon I've added yours too
![Capture d’écran, le 2022-04-03 à 13 33 30](https://user-images.githubusercontent.com/83324179/161440535-88b48433-bb4b-44fe-a16a-313e81ea9dd5.png)

**Comment by Deanskond** [comment]
Awesome. Thanks YOU.

**Comment by Lycraon** [comment]
**Thank you!**

_P.S.: Funny you knew i woul read this, GitHub sends me no notification when I'm mentioned_

**Comment by pupgray** [comment]
User agent is added!
