### ISSUE TITLE
[Suggestion] Save image id and/or link to e621 page

### ISSUE THREAD

**Issue by Deanskond** [PawCorp/walltaker#22]
Adding direct link to page would for example skip need to use reverse image search if someone got something interesting and want to see other things of the same author.

**Comment by pupgray** [comment]
There's a few ways I could do this, currently I only save the md5 of the post, might be able to send people to the md5 search page on e621, or I could start saving the post ID as well, looking into it

**Comment by oddpawsx** [comment]
For reference, the desktop client's "open e621 post" function just uses the md5 search, since the post ID wasn't there. That seems to work well if you don't want to add more to the data.

**Comment by pupgray** [comment]
Oh sorry! This is now fixed actually, there's a link to open the post on the link detail page
![Capture d’écran, le 2022-05-20 à 11 38 32](https://user-images.githubusercontent.com/83324179/169563251-545d086b-8a8f-441f-97b0-551c166f68ea.png)
