### ISSUE TITLE
[Custom Client] Wallpaper-Engine

### ISSUE THREAD

**Issue by Lycraon** [PawCorp/walltaker#24]
Hi.

I saw that you added the Automate client to your user-Agent list.
I edited my header to a similar format. (pleas say if i should edit something.),
maybe you could add mine too.

P.S: For issue with symbols flickering
save last user-agents in some time fo example 5min. and show symbols next to each other.
(in that case just don't show text next to it to save space).

You could show client-info on hover over icon.

and add code that only reloads reaction when reaction changed

**Comment by Lycraon** [comment]
Just learned that (Wallpaper-Engine)Browser overrides User-Agent i would send agent over parameters:

GET https://walltaker.joi.how/links/{linkID}.json?user_agent=walltaker-wallpaper-engine&agent_version=v0.0.2

**Comment by pupgray** [comment]
Hi! Of course!!

What icon would you like to show? https://ionic.io/ionicons

As for the user agent, could you instead add it as a header? Maybe this:

```
Wallpaper-Engine-Client: 0.0.2
```

**Comment by Lycraon** [comment]
## Icon
Propably `<ion-icon name="cog-outline"></ion-icon>`

### Font-Awesome
ionicions remebers me of FontAwesome https://fontawesome.com/
in case you need more icons

## Header
Added custom header (**Wallpaper-Engine-Client: v0.0.2**)
I have no way to see if the header gets send, so i hope it works.
Left parameters in for now just in case,

**Comment by Lycraon** [comment]
If you can use any icon 
https://icons8.com/icon/jQspry5Tmnu5/wallpaper-engine

**Comment by pupgray** [comment]
Cool! I've started saving that new header, I'll add the icon later tonight!

**Comment by Lycraon** [comment]
Had to replace - with _ in header because of error
