### ISSUE TITLE
[Enhancement] Online Status next to friends on friends page

### ISSUE THREAD

**Issue by Lycraon** [PawCorp/walltaker#25]
Would be nice to see if friends are online on Friends page

**Comment by pupgray** [comment]
This would be pretty rough on the database in the current set up, I'll have to do some performance testing before rolling this out, will get back to you!

**Comment by pupgray** [comment]
Done!
This was implemented as an async api call, so online status will appear a second after the page loads. this saves my poor postgresql instance 🐘 having to do a join for every friend all at once, now puma can split up your friends between multiple ruby instances, and be able to kill long running requests if they take too long while still not breaking the website

![Capture d’écran, le 2022-04-15 à 11 49 35](https://user-images.githubusercontent.com/83324179/163592614-f0745ef5-a875-4ca7-9a28-12443a51a384.png)
