### ISSUE TITLE
[Enhancement] Confirm dialog on friendship termination

### ISSUE THREAD

**Issue by Lycraon** [PawCorp/walltaker#26]
A while ago on smartphone i accidentally deleted a friendship.
Would be nice to get asked if i really want to terminate friendship.

**Comment by pupgray** [comment]
Good idea! Added to the roadmap!

**Comment by pupgray** [comment]
Added, and closing
<img width="734" alt="Capture d’écran, le 2022-04-07 à 20 25 05" src="https://user-images.githubusercontent.com/83324179/162339955-b603f5ab-6bf9-4692-afc2-eb4edbc1cd30.png">
!
