### ISSUE TITLE
[Bug] Generated TOML file should have Discord Presence set to False by Default

### ISSUE THREAD

**Issue by oddpawsx** [PawCorp/walltaker#27]
To match the default .toml file in the [Desktop Client repo](https://github.com/PawCorp/walltaker-desktop-client/blob/main/walltaker.toml), please consider setting `discordPresence = false` in the default generated TOML (and also consider bringing in the [recent changes to the comments denoting default values](https://github.com/PawCorp/walltaker-desktop-client/commit/94c72f884696ffee80cac245fb6233e887b823b0) on the develop branch. 

https://github.com/PawCorp/walltaker/blob/4bb41f1f1a84e78d4dcec936788107d5c82bc0af/app/views/links/export.html.erb#L37

**Comment by pupgray** [comment]
Done!
