### ISSUE TITLE
I think Hate it feedback shouldn't actually be displayed the way it is.

### ISSUE THREAD

**Issue by Deanskond** [PawCorp/walltaker#29]
Now it may seem rather confusing. As it's displayed under previous image (since the 'hated' one was removed) it may be seen as related to that image.

**Comment by pupgray** [comment]
Hmm, that's a good point but I'm not sure of a way to display that more clearly. I could include text that says something about "disliked a deleted wallpaper"?

**Comment by pupgray** [comment]
OK so phase 1 of tackling this is done! I now have notifications which can display reactions from links you've posted on:
<img width="355" alt="Capture d’écran, le 2022-04-12 à 02 20 15" src="https://user-images.githubusercontent.com/83324179/162893680-d30f3eff-ea2d-4197-93d7-1b0405388d5e.png">

This will allow me to hide only the "hate it" feedback messages on the actual link page, so only the love it + cum messages are shown publically. The hate it messages will only be in notifications

**Comment by pupgray** [comment]
And deployed! Hate it messages are no longer showed publically, but only get sent to notifications
