### ISSUE TITLE
[Enhancement] Some sort of simple chat?

### ISSUE THREAD

**Issue by meckrisa** [PawCorp/walltaker#30]
A really simple chat that could be used to communicate between friends would be great, since right now the only way is to use image feedback or go off site.

**Comment by pupgray** [comment]
I've added notifications for friend events and image feedback events!

I'll think about maybe expanding that into a chat system, will put in "researching"

**Comment by meckrisa** [comment]
Absolute legend. Been loving this app ever since I started using it, and I'm so glad to see it improve.

**Comment by Deanskond** [comment]
I was thinking about something similar but much more primitive: option to send message along the  wallpaper

**Comment by pupgray** [comment]
And I've started on this! I've decided to keep it bound to links for now, since I really don't want to have to moderate private messages.

You can follow progress on branch [feat/link-chat](https://github.com/PawCorp/walltaker/tree/feat/link-chat)!

**Comment by pupgray** [comment]
Woo! Simple link chat set up! Check out any link page!
<img width="167" alt="Capture d’écran, le 2022-04-30 à 13 42 32" src="https://user-images.githubusercontent.com/83324179/166117092-478ae9fa-e4ea-4e5c-97cd-ebebb34389b0.png">
<img width="537" alt="Capture d’écran, le 2022-04-30 à 13 33 24" src="https://user-images.githubusercontent.com/83324179/166117095-0ac8edd8-0004-4cd7-913c-ee44654c17e5.png">
!
