### ISSUE TITLE
[Enhancement] Recent image warning

### ISSUE THREAD

**Issue by gios2** [PawCorp/walltaker#32]
It would be nice to get a warning, when changing an image, that warns you if it has already been set recently, to avoid setting the same images to someone over and over again without noticing, it could be something like "This image has already been set recently, do you want to set it anyway?"

**Comment by pupgray** [comment]
Good idea! This would be a quick win, I've added it to the short term todo list

**Comment by pupgray** [comment]
<img width="576" alt="Capture d’écran, le 2022-05-19 à 23 25 19" src="https://user-images.githubusercontent.com/83324179/169444339-354f9ba0-9150-488f-9dc2-20b3e020a935.png">

Set up something basic! Currently it only affects the porn search, and will ask for confirmation if it's being set within a minute of the last setting (by any user)
