### ISSUE TITLE
[Enhancement] Clear all Notifications

### ISSUE THREAD

**Issue by Lycraon** [PawCorp/walltaker#36]
Would help to be able to clear all Notifications. they can add up pretty fast.
I simpe button under notifications would be enougth.

**Comment by pupgray** [comment]
<img width="371" alt="Capture d’écran, le 2022-05-19 à 22 35 10" src="https://user-images.githubusercontent.com/83324179/169437378-df6f6358-a460-4dbc-9fb8-8f796e1f7a7e.png">

Done!
