### ISSUE TITLE
[Enhancement] Reward system

### ISSUE THREAD

**Issue by gios2** [PawCorp/walltaker#41]
It would be nice to add an _reward system_ for those who change many images to many users, using a system of badges (5, 10, 20, 30, 40, 50, 100), next to the user's name and if possible prioritize the user in the browse tab.

**Comment by pupgray** [comment]
I like the idea of a reward like higher positioning on the browse list! This awards system will be the next big feature push

**Comment by pupgray** [comment]
Part one merged in!

Next things will be:
- Leaderboard
- Changing sorting rules on browse page to favour high-medal-ed users

**Comment by pupgray** [comment]
Leaderboard is online!
![Capture d’écran, le 2022-05-23 à 17 44 17](https://user-images.githubusercontent.com/83324179/169910673-43a3a39c-abf7-482e-809d-c648d2f1f51b.png)

**Comment by pupgray** [comment]
[49a6a1e](https://github.com/PawCorp/walltaker/commit/49a6a1e3bcaece65725b29b0b8d1e00e41782f89) now introduces the set count into the browse page ordering!

ORDER BY `last_wallpaper_timestamp - (set_count * 20 secs)` descending earliest to latest
