### ISSUE TITLE
[Bug] !Important!  private links and expired links are return by api

### ISSUE THREAD

**Issue by Lycraon** [PawCorp/walltaker#42]
When requesting https://walltaker.joi.how/api/users/[username].json the links array includes private and expired links.

So if i fetch the json for an user i can see all their links and so get all infos of the links.
I would prefer to send an api_key in the same way i send them for reactions, 
so it only shows links based on the rights of the api user
no api would be public info

**Comment by pupgray** [comment]
Fixed!
