### ISSUE TITLE
[Enhancement] Open/pending Requests

### ISSUE THREAD

**Issue by Lycraon** [PawCorp/walltaker#44]
Would be good to  see your requests you send to others in https://walltaker.joi.how/friendships/requests, that arend declined or accepted yet. 

So i know if i already send somone a request.

**Comment by pupgray** [comment]
For anyone who might want to make a PR:
This is handled by the friendships controller, you could make a new action, to render a list of friendships similarly to the `requests` action, but using:

```ruby
Friendship.all.where(sender: current_user).where(confirmed: [nil, false])
#                    ^ `sender` rather than `receiver` to get requests sent BY current user
```

as your friendship list. Bonus points for a delete button.
