### ISSUE TITLE
[Enhancement]  Change Password & Forgot Password option

### ISSUE THREAD

**Issue by Lycraon** [PawCorp/walltaker#46]
Changes Options would be on profile.
Forgott Password sends password to Email.

**Comment by oddpawsx** [comment]
For security reasons, plaintext password should never be sent via email; instead, if this is to be implemented, I strongly encourage emailing a link to reset a password instead.

**Comment by Lycraon** [comment]
Yeah you are right that would be the proper way to do things.

**Comment by pupgray** [comment]
To add to that, I have no way of even knowing what the passwords are. All passwords are bcrypt hashes.

Any password reset feature will be token based:
1. User clicks "forgot my password"
2. They enter their email
3. Associated user row gets a new random password reset token assigned, and I send an email with a link to a password reset page containing that token, to the user's email
4. Password reset form only works if token matches and has not been used before/too old

**Comment by pupgray** [comment]
Going to have to get email working here. This may be more annoying than it seems at first, since I don't exactly want to have to open an account with postmark or something considering I have to explain what this app is lol. So will look into ye olde mailgun or something

**Comment by pupgray** [comment]
https://walltaker.joi.how/i-forgor

It's set up!
