### ISSUE TITLE
[Bug] Problems with Tags

### ISSUE THREAD

**Issue by Lycraon** [PawCorp/walltaker#47]
<img width="667" alt="image" src="https://user-images.githubusercontent.com/80824508/170472351-38351083-06a1-44bb-9030-82aafcfeaa4e.png">

Theme tag/blacklist seems to be broken
Setting theme tag to "rating:s" OR blacklist to "rating:e rating:q" has no effect

**Comment by pupgray** [comment]
Will need to change from comparing tag arrays on posts to using a api search to check if blacklist filters out the post in question

**Comment by pupgray** [comment]
omg, it's done

Filtering is now done with an E621 search, not by matching tags locally, so all search features now work!
