### ISSUE TITLE
[Bug] The links are no longer clickable with the mouse wheel

### ISSUE THREAD

**Issue by gios2** [PawCorp/walltaker#57]
The links are no longer clickable with the mouse wheel to open the link in another tab, not even by right clicking, in both cases the link is not selected but the image behind it (it bothers me to go back and forth continuously)

**Comment by pupgray** [comment]
I just pushed a few fixes for this

It should work again for /links and /user/x/links, but may not working on the browse page still, working on it

![Capture d’écran, le 2022-09-18 à 13 17 30](https://user-images.githubusercontent.com/83324179/190920650-ce5143a2-ac2e-434c-8344-0d2b19f967b9.png)

**Comment by pupgray** [comment]
This is now fixed with the new browse pros layout!
