### ISSUE TITLE
[suggestion] use shortcuts for ios

### ISSUE THREAD

**Issue by zeratax** [PawCorp/walltaker#61]
maybe this is more of a question ^^
but i am wondering if shortcuts could be used instead of a widget 
![ios shortcut app](https://user-images.githubusercontent.com/5024958/232817113-d38da2bd-1946-40e4-91e4-3effda2afc3a.png)
this shortcut sets my wallpaper to my current walltaker. with automations i can even let this run at specific times of the day. 
![EAF119D1-6312-4AF6-ADAA-C0EE1250A209](https://user-images.githubusercontent.com/5024958/232817813-8df075e4-5d39-41f5-82a1-a931714f80ff.png)

sadly i can’t set it every n minutes. i could only set up an automation for every n minutes, which is ofc annoying.

**Comment by pupgray** [comment]
Yes! Shortcuts totally work! I was actually using this for a while before I got the iOS widget hack working. Feel free to share your shortcut!! I'm happy to add it as a client!
