### ISSUE TITLE
[Enhancement] Maybe expanding to Furaffinity 

### ISSUE THREAD

**Issue by Zenko01** [PawCorp/walltaker#63]
It may not be possible but it would be an idea to use the Picture IDs from Furaffinity too since they are identical almost so we would have more options and also wouldn't necessarily encounter a lot of repeated Pictures and would have access to newer stuff that doesn't exist on E621

**Comment by pupgray** [comment]
FA's tagging rules are too loose, there would be a lot more abuse.
