### ISSUE TITLE
[Enhancement] 

### ISSUE THREAD

**Issue by Reapacoon** [PawCorp/walltaker#64]
Using the webapp, And am realizing it's quite easy for trolls to plague you with unwanted images. I feel like a setting to allow only verified users might help with this. perhaps also a block system.

**Comment by pupgray** [comment]
The blacklist and friends only links are the main tools against abuse. Setting up an account is basically a 30 second task, so it doesn't limit anything, and will create a false sense of security. I can't promise there won't be trolls. It's actually baked into the concept, it's relinquishing some control to the internet.
